name: zyrthi/hal
version: "0.1.0"
description: Hardware Abstraction Layer for embedded systems
license: MIT

platform: any
board: any

dependencies: {}

repositories:
  - name: central
    url: https://dehub-io.github.io/dehub-repository/

# 纯头文件库
include: include
